### ISSUE TITLE
Assassin: Pain Rune Turns Target

### ISSUE THREAD

**Issue by Yoress** [Yoress/friendly-dollop#47]
**1.) Bug Description**
"Assassin's Pain Rune skill turns targets around sometimes" ~ H

**2.) What you think the intended behaviour should be**
If this skill is meant to move targets at all, it should not make them change direction.

**Comment by alexangc** [comment]
I've started investigating this one. It's strange because it didn't exist in the v3.9 of the EMU I had ...

I haven't given it a lot of time, but after debugging the server-side position of the mobs, it seems that the stun in itself isn't the cause of the faulty orientation, but instead only reveals it. I think I had moments when the mob's position was wrong on server side, but wasn't reflected on client-side.

**Comment by alexangc** [comment]
In fact, the server does not seem to update the heading of NPCs when they attack. Instead, the client most likely extrapolates it based on the mob's position and it's target's.

So if a mob attacks you without moving from its idle position _(because you came in hide, or it didn't have time to aggro you before you got in range)_, then when you stun it, the server-side heading will be broadcast and your client will update its own.

I am not sure if it is the only reason for the bug, but at least it seems to be one reason. I am not sure yet about how to fix this properly though, but I'll figure it next time.
